### ISSUE TITLE
Deprecated compile !

### ISSUE THREAD

**Issue by stevebaros** [JakeWharton/jax-rs-kotlinx-serialization#2]
`compile 'com.jakewharton:jax-rs-kotlinx-serialization:0.1.0'`

`implementation 'com.jakewharton:jax-rs-kotlinx-serialization:0.1.0' `

**Comment by JakeWharton** [comment]
Fixed in 6affef8e33c104e8b1c39846b1d04f2f054be44f. Thanks.
